package presentation;

import base.ConnexionBase;
import base.DepartementDao;
import base.EmployeDao;
import base.FonctionDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 634.1 Programmation - TP P01
 * 
 * Fenêtre de saisie d'un nouvel employé:
 * - Singleton
 * 
 * @author Eric Mclaren - HEG Genève
 * @version 1.0
 */
public class FrmNouveau extends java.awt.Frame {
    private FrmMain frmMain;
    private static FrmNouveau INSTANCE = null;
    private static ArrayList fonctions;
    private static ArrayList departements;
    /* Constructeur */
    private FrmNouveau () {
        initComponents();
        initFonc();
        initDept();
    } // Constructeur

    public static FrmNouveau getInstance(FrmMain frmMain){
        if(INSTANCE == null){
            INSTANCE = new FrmNouveau();
        }
        INSTANCE.frmMain = frmMain;
        return INSTANCE;
    }
    
    public static void initFonc(){
        fonctions = FonctionDao.getFonctions();
        for(int i = 0; i<fonctions.size(); i++){
            chFonctions.add(fonctions.get(i).toString());
        }
    }
    
    public static void initDept(){
        departements = DepartementDao.getDepartements();
        for(int i = 0; i<departements.size(); i++){
            chDepartements.add(departements.get(i).toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        java.awt.Label label1 = new java.awt.Label();
        java.awt.Label label2 = new java.awt.Label();
        lblDateEngagement = new java.awt.Label();
        java.awt.Label label4 = new java.awt.Label();
        java.awt.Label label5 = new java.awt.Label();
        btnEnregistrer = new java.awt.Button();
        tfNom = new java.awt.TextField();
        tfPrenom = new java.awt.TextField();
        tfDateEngagement = new java.awt.TextField();
        chFonctions = new java.awt.Choice();
        chDepartements = new java.awt.Choice();

        setResizable(false);
        setTitle("Saisie d'un employé");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setText("Nom");

        label2.setText("Prénom");

        lblDateEngagement.setText("Date d'engagement");

        label4.setText("Fonction");

        label5.setText("Département");

        btnEnregistrer.setEnabled(false);
        btnEnregistrer.setLabel("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        tfNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomKeyReleased(evt);
            }
        });

        tfPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrenomKeyReleased(evt);
            }
        });

        tfDateEngagement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDateEngagementKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chFonctions, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tfDateEngagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chDepartements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chDepartements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowClosing(java.awt.event.WindowEvent evt) {  
        dispose();
    }                                  

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        String nom = tfNom.getText();
        String prenom = tfPrenom.getText();
        String dateEngagement = tfDateEngagement.getText();
        int nomFonction = chFonctions.getSelectedIndex();
        int nomDepartement = chDepartements.getSelectedIndex();
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        Date d = new Date();
        try {
            d = f.parse(dateEngagement);
        } catch (ParseException ex) {
            Logger.getLogger(FrmNouveau.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date dateEngagementD = d;
        EmployeDao.saveEmploye(nom, prenom, dateEngagementD, nomFonction, nomDepartement);
        frmMain.resetEmployes(nom + " " + prenom);        
        dispose();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void tfNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomKeyReleased
        checkSave();
    }//GEN-LAST:event_tfNomKeyReleased

    private void tfPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrenomKeyReleased
        checkSave();
    }//GEN-LAST:event_tfPrenomKeyReleased

    private void tfDateEngagementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDateEngagementKeyReleased
        checkSave();
    }//GEN-LAST:event_tfDateEngagementKeyReleased

    private Date valideDate(String date){
        SimpleDateFormat f = new SimpleDateFormat("dd.MM.yyyy");
        Date d = new Date();
        try {
            d = f.parse(date);
            return d;
        } catch (ParseException ex) {
            return null;
        }
    }
    
    private void checkSave(){
        if(tfNom.getText().length()>0 && tfPrenom.getText().length()>0 && tfDateEngagement.getText().length()>0){
            String dateEngagement = tfDateEngagement.getText();
            Date valid = valideDate(dateEngagement);
            if(valid!=null && valid.before(new Date()) ){
                btnEnregistrer.setEnabled(true); 
            }else{
                btnEnregistrer.setEnabled(false);
            }
        }else{
            btnEnregistrer.setEnabled(false);   
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnregistrer;
    private static java.awt.Choice chDepartements;
    private static java.awt.Choice chFonctions;
    private java.awt.Choice choice1;
    private java.awt.Label lblDateEngagement;
    private static java.awt.TextField tfDateEngagement;
    private static java.awt.TextField tfNom;
    private static java.awt.TextField tfPrenom;
    // End of variables declaration//GEN-END:variables

} // FrmNouveau
